import "./globals.css";
import type { Metadata } from "next";
import ReactQueryProvider from "./components/ReactQueryProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Concert Dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          {children}
          <Toaster position="top-right" richColors />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
